/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenterRouteImport } from './routes/renter'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RenterDashboardRouteImport } from './routes/renter.dashboard'
import { Route as RenterBookingsRouteImport } from './routes/renter.bookings'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalCustomersRouteImport } from './routes/portal.customers'
import { Route as PortalCarsRouteImport } from './routes/portal.cars'
import { Route as PortalBookingsRouteImport } from './routes/portal.bookings'

const CarsCarIdLazyRouteImport = createFileRoute('/cars/$carId')()

const RenterRoute = RenterRouteImport.update({
  id: '/renter',
  path: '/renter',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CarsCarIdLazyRoute = CarsCarIdLazyRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cars.$carId.lazy').then((d) => d.Route))
const RenterDashboardRoute = RenterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RenterRoute,
} as any)
const RenterBookingsRoute = RenterBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => RenterRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCustomersRoute = PortalCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCarsRoute = PortalCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/renter': typeof RenterRouteWithChildren
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/cars': typeof PortalCarsRoute
  '/portal/customers': typeof PortalCustomersRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/cars/$carId': typeof CarsCarIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/renter': typeof RenterRouteWithChildren
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/cars': typeof PortalCarsRoute
  '/portal/customers': typeof PortalCustomersRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/cars/$carId': typeof CarsCarIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/renter': typeof RenterRouteWithChildren
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/cars': typeof PortalCarsRoute
  '/portal/customers': typeof PortalCustomersRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/cars/$carId': typeof CarsCarIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/renter'
    | '/portal/bookings'
    | '/portal/cars'
    | '/portal/customers'
    | '/portal/dashboard'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/cars/$carId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/renter'
    | '/portal/bookings'
    | '/portal/cars'
    | '/portal/customers'
    | '/portal/dashboard'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/cars/$carId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/renter'
    | '/portal/bookings'
    | '/portal/cars'
    | '/portal/customers'
    | '/portal/dashboard'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/cars/$carId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RenterRoute: typeof RenterRouteWithChildren
  CarsCarIdLazyRoute: typeof CarsCarIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renter': {
      id: '/renter'
      path: '/renter'
      fullPath: '/renter'
      preLoaderRoute: typeof RenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter/dashboard': {
      id: '/renter/dashboard'
      path: '/dashboard'
      fullPath: '/renter/dashboard'
      preLoaderRoute: typeof RenterDashboardRouteImport
      parentRoute: typeof RenterRoute
    }
    '/renter/bookings': {
      id: '/renter/bookings'
      path: '/bookings'
      fullPath: '/renter/bookings'
      preLoaderRoute: typeof RenterBookingsRouteImport
      parentRoute: typeof RenterRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/customers': {
      id: '/portal/customers'
      path: '/customers'
      fullPath: '/portal/customers'
      preLoaderRoute: typeof PortalCustomersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cars': {
      id: '/portal/cars'
      path: '/cars'
      fullPath: '/portal/cars'
      preLoaderRoute: typeof PortalCarsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalBookingsRoute: typeof PortalBookingsRoute
  PortalCarsRoute: typeof PortalCarsRoute
  PortalCustomersRoute: typeof PortalCustomersRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBookingsRoute: PortalBookingsRoute,
  PortalCarsRoute: PortalCarsRoute,
  PortalCustomersRoute: PortalCustomersRoute,
  PortalDashboardRoute: PortalDashboardRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface RenterRouteChildren {
  RenterBookingsRoute: typeof RenterBookingsRoute
  RenterDashboardRoute: typeof RenterDashboardRoute
}

const RenterRouteChildren: RenterRouteChildren = {
  RenterBookingsRoute: RenterBookingsRoute,
  RenterDashboardRoute: RenterDashboardRoute,
}

const RenterRouteWithChildren =
  RenterRoute._addFileChildren(RenterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RenterRoute: RenterRouteWithChildren,
  CarsCarIdLazyRoute: CarsCarIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
