/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenterRouteImport } from './routes/renter'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RenterProfileRouteImport } from './routes/renter.profile'
import { Route as RenterDashboardRouteImport } from './routes/renter.dashboard'
import { Route as RenterBookingsRouteImport } from './routes/renter.bookings'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalCustomersRouteImport } from './routes/portal.customers'
import { Route as PortalCarsRouteImport } from './routes/portal.cars'
import { Route as PortalBookingsRouteImport } from './routes/portal.bookings'
import { Route as PortalCustomersIndexRouteImport } from './routes/portal.customers.index'
import { Route as PortalCarsIndexRouteImport } from './routes/portal.cars.index'
import { Route as PortalBookingsIndexRouteImport } from './routes/portal.bookings.index'
import { Route as PortalCustomersCustomerIdRouteImport } from './routes/portal.customers.$customerId'
import { Route as PortalCarsCarIdRouteImport } from './routes/portal.cars.$carId'
import { Route as PortalBookingsOrderIdRouteImport } from './routes/portal.bookings.$orderId'

const CheckoutLazyRouteImport = createFileRoute('/checkout')()
const CarsCarIdLazyRouteImport = createFileRoute('/cars/$carId')()

const CheckoutLazyRoute = CheckoutLazyRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/checkout.lazy').then((d) => d.Route))
const RenterRoute = RenterRouteImport.update({
  id: '/renter',
  path: '/renter',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CarsCarIdLazyRoute = CarsCarIdLazyRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cars.$carId.lazy').then((d) => d.Route))
const RenterProfileRoute = RenterProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RenterRoute,
} as any)
const RenterDashboardRoute = RenterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RenterRoute,
} as any)
const RenterBookingsRoute = RenterBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => RenterRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCustomersRoute = PortalCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCarsRoute = PortalCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCustomersIndexRoute = PortalCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalCustomersRoute,
} as any)
const PortalCarsIndexRoute = PortalCarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalCarsRoute,
} as any)
const PortalBookingsIndexRoute = PortalBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalBookingsRoute,
} as any)
const PortalCustomersCustomerIdRoute =
  PortalCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => PortalCustomersRoute,
  } as any)
const PortalCarsCarIdRoute = PortalCarsCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => PortalCarsRoute,
} as any)
const PortalBookingsOrderIdRoute = PortalBookingsOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => PortalBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/renter': typeof RenterRouteWithChildren
  '/checkout': typeof CheckoutLazyRoute
  '/portal/bookings': typeof PortalBookingsRouteWithChildren
  '/portal/cars': typeof PortalCarsRouteWithChildren
  '/portal/customers': typeof PortalCustomersRouteWithChildren
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/renter/profile': typeof RenterProfileRoute
  '/cars/$carId': typeof CarsCarIdLazyRoute
  '/portal/bookings/$orderId': typeof PortalBookingsOrderIdRoute
  '/portal/cars/$carId': typeof PortalCarsCarIdRoute
  '/portal/customers/$customerId': typeof PortalCustomersCustomerIdRoute
  '/portal/bookings/': typeof PortalBookingsIndexRoute
  '/portal/cars/': typeof PortalCarsIndexRoute
  '/portal/customers/': typeof PortalCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/renter': typeof RenterRouteWithChildren
  '/checkout': typeof CheckoutLazyRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/renter/profile': typeof RenterProfileRoute
  '/cars/$carId': typeof CarsCarIdLazyRoute
  '/portal/bookings/$orderId': typeof PortalBookingsOrderIdRoute
  '/portal/cars/$carId': typeof PortalCarsCarIdRoute
  '/portal/customers/$customerId': typeof PortalCustomersCustomerIdRoute
  '/portal/bookings': typeof PortalBookingsIndexRoute
  '/portal/cars': typeof PortalCarsIndexRoute
  '/portal/customers': typeof PortalCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/renter': typeof RenterRouteWithChildren
  '/checkout': typeof CheckoutLazyRoute
  '/portal/bookings': typeof PortalBookingsRouteWithChildren
  '/portal/cars': typeof PortalCarsRouteWithChildren
  '/portal/customers': typeof PortalCustomersRouteWithChildren
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/renter/bookings': typeof RenterBookingsRoute
  '/renter/dashboard': typeof RenterDashboardRoute
  '/renter/profile': typeof RenterProfileRoute
  '/cars/$carId': typeof CarsCarIdLazyRoute
  '/portal/bookings/$orderId': typeof PortalBookingsOrderIdRoute
  '/portal/cars/$carId': typeof PortalCarsCarIdRoute
  '/portal/customers/$customerId': typeof PortalCustomersCustomerIdRoute
  '/portal/bookings/': typeof PortalBookingsIndexRoute
  '/portal/cars/': typeof PortalCarsIndexRoute
  '/portal/customers/': typeof PortalCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/renter'
    | '/checkout'
    | '/portal/bookings'
    | '/portal/cars'
    | '/portal/customers'
    | '/portal/dashboard'
    | '/portal/settings'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/renter/profile'
    | '/cars/$carId'
    | '/portal/bookings/$orderId'
    | '/portal/cars/$carId'
    | '/portal/customers/$customerId'
    | '/portal/bookings/'
    | '/portal/cars/'
    | '/portal/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/renter'
    | '/checkout'
    | '/portal/dashboard'
    | '/portal/settings'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/renter/profile'
    | '/cars/$carId'
    | '/portal/bookings/$orderId'
    | '/portal/cars/$carId'
    | '/portal/customers/$customerId'
    | '/portal/bookings'
    | '/portal/cars'
    | '/portal/customers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/renter'
    | '/checkout'
    | '/portal/bookings'
    | '/portal/cars'
    | '/portal/customers'
    | '/portal/dashboard'
    | '/portal/settings'
    | '/renter/bookings'
    | '/renter/dashboard'
    | '/renter/profile'
    | '/cars/$carId'
    | '/portal/bookings/$orderId'
    | '/portal/cars/$carId'
    | '/portal/customers/$customerId'
    | '/portal/bookings/'
    | '/portal/cars/'
    | '/portal/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RenterRoute: typeof RenterRouteWithChildren
  CheckoutLazyRoute: typeof CheckoutLazyRoute
  CarsCarIdLazyRoute: typeof CarsCarIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter': {
      id: '/renter'
      path: '/renter'
      fullPath: '/renter'
      preLoaderRoute: typeof RenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter/profile': {
      id: '/renter/profile'
      path: '/profile'
      fullPath: '/renter/profile'
      preLoaderRoute: typeof RenterProfileRouteImport
      parentRoute: typeof RenterRoute
    }
    '/renter/dashboard': {
      id: '/renter/dashboard'
      path: '/dashboard'
      fullPath: '/renter/dashboard'
      preLoaderRoute: typeof RenterDashboardRouteImport
      parentRoute: typeof RenterRoute
    }
    '/renter/bookings': {
      id: '/renter/bookings'
      path: '/bookings'
      fullPath: '/renter/bookings'
      preLoaderRoute: typeof RenterBookingsRouteImport
      parentRoute: typeof RenterRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/customers': {
      id: '/portal/customers'
      path: '/customers'
      fullPath: '/portal/customers'
      preLoaderRoute: typeof PortalCustomersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cars': {
      id: '/portal/cars'
      path: '/cars'
      fullPath: '/portal/cars'
      preLoaderRoute: typeof PortalCarsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/customers/': {
      id: '/portal/customers/'
      path: '/'
      fullPath: '/portal/customers/'
      preLoaderRoute: typeof PortalCustomersIndexRouteImport
      parentRoute: typeof PortalCustomersRoute
    }
    '/portal/cars/': {
      id: '/portal/cars/'
      path: '/'
      fullPath: '/portal/cars/'
      preLoaderRoute: typeof PortalCarsIndexRouteImport
      parentRoute: typeof PortalCarsRoute
    }
    '/portal/bookings/': {
      id: '/portal/bookings/'
      path: '/'
      fullPath: '/portal/bookings/'
      preLoaderRoute: typeof PortalBookingsIndexRouteImport
      parentRoute: typeof PortalBookingsRoute
    }
    '/portal/customers/$customerId': {
      id: '/portal/customers/$customerId'
      path: '/$customerId'
      fullPath: '/portal/customers/$customerId'
      preLoaderRoute: typeof PortalCustomersCustomerIdRouteImport
      parentRoute: typeof PortalCustomersRoute
    }
    '/portal/cars/$carId': {
      id: '/portal/cars/$carId'
      path: '/$carId'
      fullPath: '/portal/cars/$carId'
      preLoaderRoute: typeof PortalCarsCarIdRouteImport
      parentRoute: typeof PortalCarsRoute
    }
    '/portal/bookings/$orderId': {
      id: '/portal/bookings/$orderId'
      path: '/$orderId'
      fullPath: '/portal/bookings/$orderId'
      preLoaderRoute: typeof PortalBookingsOrderIdRouteImport
      parentRoute: typeof PortalBookingsRoute
    }
  }
}

interface PortalBookingsRouteChildren {
  PortalBookingsOrderIdRoute: typeof PortalBookingsOrderIdRoute
  PortalBookingsIndexRoute: typeof PortalBookingsIndexRoute
}

const PortalBookingsRouteChildren: PortalBookingsRouteChildren = {
  PortalBookingsOrderIdRoute: PortalBookingsOrderIdRoute,
  PortalBookingsIndexRoute: PortalBookingsIndexRoute,
}

const PortalBookingsRouteWithChildren = PortalBookingsRoute._addFileChildren(
  PortalBookingsRouteChildren,
)

interface PortalCarsRouteChildren {
  PortalCarsCarIdRoute: typeof PortalCarsCarIdRoute
  PortalCarsIndexRoute: typeof PortalCarsIndexRoute
}

const PortalCarsRouteChildren: PortalCarsRouteChildren = {
  PortalCarsCarIdRoute: PortalCarsCarIdRoute,
  PortalCarsIndexRoute: PortalCarsIndexRoute,
}

const PortalCarsRouteWithChildren = PortalCarsRoute._addFileChildren(
  PortalCarsRouteChildren,
)

interface PortalCustomersRouteChildren {
  PortalCustomersCustomerIdRoute: typeof PortalCustomersCustomerIdRoute
  PortalCustomersIndexRoute: typeof PortalCustomersIndexRoute
}

const PortalCustomersRouteChildren: PortalCustomersRouteChildren = {
  PortalCustomersCustomerIdRoute: PortalCustomersCustomerIdRoute,
  PortalCustomersIndexRoute: PortalCustomersIndexRoute,
}

const PortalCustomersRouteWithChildren = PortalCustomersRoute._addFileChildren(
  PortalCustomersRouteChildren,
)

interface PortalRouteChildren {
  PortalBookingsRoute: typeof PortalBookingsRouteWithChildren
  PortalCarsRoute: typeof PortalCarsRouteWithChildren
  PortalCustomersRoute: typeof PortalCustomersRouteWithChildren
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBookingsRoute: PortalBookingsRouteWithChildren,
  PortalCarsRoute: PortalCarsRouteWithChildren,
  PortalCustomersRoute: PortalCustomersRouteWithChildren,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalSettingsRoute: PortalSettingsRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface RenterRouteChildren {
  RenterBookingsRoute: typeof RenterBookingsRoute
  RenterDashboardRoute: typeof RenterDashboardRoute
  RenterProfileRoute: typeof RenterProfileRoute
}

const RenterRouteChildren: RenterRouteChildren = {
  RenterBookingsRoute: RenterBookingsRoute,
  RenterDashboardRoute: RenterDashboardRoute,
  RenterProfileRoute: RenterProfileRoute,
}

const RenterRouteWithChildren =
  RenterRoute._addFileChildren(RenterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RenterRoute: RenterRouteWithChildren,
  CheckoutLazyRoute: CheckoutLazyRoute,
  CarsCarIdLazyRoute: CarsCarIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
